bindPort = 7000
bindAddr = "0.0.0.0"
kcpBindPort = 2333
webServer.addr = "0.0.0.0"
webServer.port = 7500
webServer.user = "admin"
webServer.password = "admin"

vhostHTTPPort = 80
vhostHTTPSPort = 443

mefrpApi.apiUrl = ""
mefrpApi.token = "MEFrpToken"
mefrpApi.nodeId = 1
