FROM golang:1.20 AS building

COPY . /building
WORKDIR /building

RUN make frps

FROM alpine:3

RUN apk add --no-cache tzdata

COPY --from=building /building/bin/mefrps /usr/bin/mefrps

ENTRYPOINT ["/usr/bin/mefrps"]
