FROM golang:1.20 AS building

COPY . /building
WORKDIR /building

RUN make frpc

FROM alpine:3

RUN apk add --no-cache tzdata

COPY --from=building /building/bin/mefrpc /usr/bin/mefrpc

ENTRYPOINT ["/usr/bin/mefrpc"]
