name: build

on:
  workflow_dispatch:

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'

      - name: Make All
        run: |
          ./package.sh

      - name: Upload Frp Client
        uses: actions/upload-artifact@v4
        with:
          name: mefrpc
          path: ./release/packages/mefrpc_*

      - name: Upload Frp Server
        uses: actions/upload-artifact@v4
        with:
          name: mefrps
          path: ./release/packages/mefrps_*