name: goreleaser

on:
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
          
      - name: Make All
        run: |
          ./package.sh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: mefrp-core-next
          path: ./release/packages/*
